[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "alphaminustwo"
version = "1.0.0"
dependencies = []

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.package-data]
"*" = ["py.typed"]

